version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: horizon_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8246
      POSTGRES_DB: horizon_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: horizon_redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  bot:
    build: .
    container_name: horizon_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./image:/app/image
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data: